/* Copyright 2020 - 2025, Saxon Software. All rights reserved. */

#pragma once

enum FileOpenRules
{
	OPENRULE_READ = 1 << 0,
	OPENRULE_WRITE = 1 << 1,
	OPENRULE_DELETE = 1 << 2

};

enum FileOverrideRules
{
	OVERRIDERULE_JUST_OPEN,
	OVERRIDERULE_OPEN_ONLY_IF_EXISTS,
	OVERRIDERULE_CREATE_NEW_IF_NOT_EXISTS,
	OVERRIDERULE_CREATE_NEW_DONT_MIND

};

enum FileStatus
{
	FILESTATUS_NONE,
	FILESTATUS_PROCESSING,
	FILESTATUS_NOT_FOUND,
	FILESTATUS_ALREADY_EXISTS,
	FILESTATUS_GOOD,
	FILESTATUS_ERROR,
	FILESTATUS_DIED

};
